version: '3.1'

services:
    db:
        image: mariadb:latest
        restart: always
        volumes: 
            - ./mariadb/data/:/var/lib/mysql/
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=myDB
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=password
        ports: 
            - '3306:3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        # environment:
        #     - PMA_HOST=db

networks: 
    default:
        external: 
            name:
                web_network
